asn1crypto/keys.py, tests/test_keys.py
Here's a pass at PrivateKeyInfo.public_key_info. Two interesting things to note:
1. PublicKeyInfo overrides the public_key field spec for ec keys, so we can't assign a ParsableOctetBitString to the public_key field in wrap(). I narrowed the definition to require a public_key that matches the value spec. This method was not previously covered by unit tests, so it's hard to know if the original definition was actually working.
2. The unit test has to compare .dump() rather than .native (which doesn't match for some algorithms). I'm not sure if native representations are guaranteed to be canonical, so maybe it's just an idiosyncrasy in generating native representations after mutating a container.
Thanks,
Peter
=> Add .public_key_info accessor to PrivateKeyInfo.

tests/fixtures/cms-signed-indefinite-length.der, tests/test_cms.py
Hi,
I've a problem with a .p7m that make asn1crypto explode with 
ValueError: Insufficient data - 57904015269414514108800405237541285051975119636830231669355043598084451101117 bytes requested but only 57362 available
IMHO the problem is related to the parsing of a length octet with indefinite length, however I'm unable to fix it myself.
openssl has no problem handling the (original) file.  The file added with this pull request has been changed to anonymize some data so don't be surprised if the signature cannot be verified.
ciao
walter
=> test file that let _parse_children raise an exception

asn1crypto/x509.py, tests/test_x509.py
x509.Name.build() sensibly advertises that it accepts OIDs in string form in addition to well-known attribute names. Except it actually just ignores them. There are a number of ways to fix this, I imagine; here's one.
Thanks,
Peter
=> Support OIDs in x509.Name.build() (as documented)

asn1crypto/x509.py
It's a little known secret that startswith() and endwith() take a tuple
of arguments, too.
=> Support ldaps and make matching nicer

readme.md
For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html
=> Update all pypi.python.org URLs to pypi.org

asn1crypto/algos.py
These algorithm identifiers are from https://csrc.nist.gov/projects/computer-security-objects-register/algorithm-registration . I've also compared them to the OIDs in openssl (which credits them to a different URL but also at NIST).
(The SHAKE algorithms are also part of the SHA-3 / Keccak family.)
=> Add NIST OIDs for SHA-3 (and SHAKE) algorithms.

asn1crypto/keys.py
For #129 . Found named curve at https://www.flexiprovider.de/CurvesGfpSEC2.html#secp256k1.
I could also add the base point for key derivation if it is of interest but I'm not really using it.
=> Add reference to secp256k1

asn1crypto/cms.py
now windows pe file are signed with both sha1 and sha256.
=> support windows pe file nested sha256 signature

asn1crypto/util.py, tests/test_core.py
If a timezone object is copied, its __reduce__ method is called which in
turn calls __getinitargs__ to get arguments for __init__ on the new
object.
If that function is missing, __init_ is called with too few parameters.
Problem can be triggered by calling copy or untag on UTCTime or GeneralizedTime
or any other object where the native value includes a datetime
Fixes #167
=> Add __getinitargs__ method to util.timezone

.travis.yml
Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI for Python 3.7.
=> Added arm64 jobs in Travis-CI

asn1crypto/x509.py
This worked for now, but is SyntaxError in Python 3.9.0a6:
```
File "/usr/lib/python3.9/site-packages/asn1crypto/x509.py", line 1139
return', '.join(
^
SyntaxError: invalid string prefix
```
(The Python change might actually be [reverted](https://github.com/python/cpython/pull/19888) before 3.9 final, but this can be fixed anyway.)
=> Fix a syntax typo

.travis.yml
As with ARM64, Travis CI supports ppc64le ("Power") now.
I've just mimicked the job that ARM64 does, I think that provides decent coverage without bloating the test matrix too much. (We could also test pypy on Power, but I don't think it gets us too much extra value.)
If any issues come up with the Power build in future, feel free to tag me in and I'll have a look - I have access to Power systems at work.
=> Add ppc64le jobs to Travis CI

asn1crypto/core.py, tests/test_core.py
X.660 §7.6 specifies that the first arc of an OID must be 0 to 2 and
the second arc below arcs 0 and 1 must be 0 to 39. Arc 2 is not
restricted in that way.
The algorithm for parsing ObjectIdentifiers did not work for
OID 2.X with X >= 40.
This change also enforces above restrictions when setting an
ObjectIdentifier.
=> Fix parsing of ObjectIdentifier's first octet.

asn1crypto/x509.py
`organization` key does not exists in `NameType`, so actually using it results in it trying to be parsed as an int
=> fix example for Name dict

asn1crypto/parser.py, tests/test_parser.py
This PR contains a handful of commits that are probably best reviewed individually. They are:
* Fix missing bounds checks in parser
* Bound the recursion depth when walking indefinite-length encoding
* Fix indefinite-length parsing 
* Forbid indefinite-length primitive elements
* Tags must be minimally encoded
=> Fix various issues in the parser

asn1crypto/cms.py, tests/test_cms.py
This PR rectifies two incorrect applications of the 'implicit tags' tagging default declared in the X.509 ASN.1 module (EDIT: the relevant definitions are also reproduced in RFC 5755).
Concretely, it updates the `asn1crypto` definitions of `RoleSyntax` and `SecurityCategory`. As stipulated in ITU-T Rec. X.680 § C.3.2.2 (g), the 'implicit tags' directive does not apply to choice types and open types, since that would make them impossible to decode reliably.
In fact, `asn1crypto` currently raises an exception when trying to encode a `RoleSyntax` value, for this exact reason.
All this PR does is change `implicit` to `explicit` in those two locations, and add a regression test.
=> Fix tagging for RoleSyntax and SecurityCategory

asn1crypto/cms.py, tests/test_cms.py
Hi there,
Here's another pull request to fix a tagging issue in some type definitions relating to attribute certificates (compare #218).
- According to RFC 5755 (which obsoletes RFC 3281) the tagging on
Clearance in RFC 3281 was wrong, and inconsistent with the definition in
the ITU Rec. X.50x series. This commit fixes the tagging to be
consistent with RFC 5755.
- The 'default' value of classList is `'unclassified'`, while it should be
`{'unclassified'}`. This caused asn1crypto to throw an error whenever
the caller would try to encode a Clearance value.
------
References for the erroneous tagging in RFC 3281 and the history of that change:
- https://datatracker.ietf.org/doc/html/rfc5755#section-4.4.6
- https://www.rfc-editor.org/errata_search.php?rfc=3281&rec_status=0 (see in particular …
=> Fix Clearance type definition

asn1crypto/core.py, tests/test_core.py
The way `asn1crypto` manages its classes does not always play nice with unpickling objects. In particular, pickled `Asn1Value`s cannot always be unpickled in a "fresh" interpreter where the class setup methods for `asn1crypto`'s classes haven't been called yet. See discussion in #239.
This commit implements `__reduce__` on Asn1Value in such a way that pickle will use `asn1crypto`'s own DER serialisation/deserialisation functionality to handle pickling and unpickling.
Fixes #239.
EDIT: Note that CI will fail until https://github.com/wbond/certvalidator/pull/42 is merged.
=> Allow better pickle integration

asn1crypto/crl.py
Update CRL versions to match RFC 5280.
See https://datatracker.ietf.org/doc/html/rfc5280#section-5.1.2.1"
Fixes #236.
=> Update CRL versions to match RFC 5280.

asn1crypto/algos.py, tests/test_x509.py
Add .cms_hash_algo as a replacement. See discussion at https://github.com/wbond/asn1crypto/pull/230 for details.
=> Remove .hash_algo for EdDSA-based signature algorithms

asn1crypto/cms.py, asn1crypto/core.py, tests/test_cms.py
Potential fix for #243 that needs a test
=> Fix duplicate definition of RecipientKeyIdentifier
